#!/bin/bash
apt-get update
apt-get -y install qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static:register --reset
cat /proc/sys/fs/binfmt_misc/* 
for qemu in $( find / -name /usr/bin/qemu-* ); do
cp $qemu bin/
done
ls bin
