#!/bin/bash
#apt-get update
#apt-get -y install qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static:register --reset
for qemu in $( find / -name qemu* ); do
cp $qemu bin/
done
ls bin
